version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cinehua_postgres
    restart: always
    environment:
      POSTGRES_USER: cinehua_user
      POSTGRES_PASSWORD: cinehua123
      POSTGRES_DB: cinehua_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cinehua_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: